#############################################################################
#  CONSUL
#
#  Consul is the service catalog that helps discovery between the components
#  Change "-bootstrap" to "-bootstrap-expect 3", then scale to 3 or more to
#  turn this into an HA Consul raft.
#############################################################################
consul:
  image: autopilotpattern/consul:0.7.2-r0.8
  command: >
    /usr/local/bin/containerpilot
    /bin/consul agent -server
      -config-dir=/etc/consul
      -log-level=err
      -bootstrap-expect 1
      -ui-dir /ui
  restart: always
  mem_limit: 128m
  ports:
    - 8500:8500
  dns:
    - 127.0.0.1

#############################################################################
#  PROMETHEUS
#
#  Prometheus is an open source performance monitoring tool
#  it is included here for demo purposes and is not required
#############################################################################
prometheus:
  image: autopilotpattern/prometheus:1.7.1-r20
  restart: always
  mem_limit: 1g
  ports:
    - 9090:9090
  links:
    - consul:consul
  environment:
    - CONSUL=consul
    - CONSUL_AGENT=1
  dns:
    - 127.0.0.1


#############################################################################
#  FRONTEND
#############################################################################
frontend:
  image: joyent/copilot-frontend:1.0.0
  mem_limit: 512m
  links:
    - consul:consul
  env_file:
    - _env
  environment:
    - CONSUL=consul
    - PORT=443
  ports:
    - "80:80"
    - "443:443"
  dns:
    - 127.0.0.1


#############################################################################
#  BACKEND
#############################################################################
api:
  image: joyent/copilot-api:1.8.8
  mem_limit: 512m
  links:
    - consul:consul
    - rethinkdb:rethinkdb
  env_file:
    - _env
  environment:
    - CONSUL=consul
    - PORT=3000
    - RETHINK_HOST=rethinkdb
  expose:
    - 3000

# Docker-compose wrapper
# Create _env file from running ./setup.sh
compose-api:
  image: joyent/copilot-compose:1.0.0
  links:
    - consul:consul
  expose:
    - 4242
  env_file:
    - _env
  environment:
    - CONSUL=consul
  restart: always

rethinkdb:
  image: autopilotpattern/rethinkdb:2.3.5r1
  restart: always
  mem_limit: 1g
  links:
    - consul:consul
  env_file:
    - _env
  environment:
    - CONSUL=consul
    - CONSUL_AGENT=1
  ports:
    - 8080:8080
  expose:
    - 28015
    - 29015
  dns:
    - 127.0.0.1
